export const LANG = {
    ru: {
        app_name: "SmartNotes",
        slogan: "Ваши мысли. В порядке.",
        login: "Вход в систему",
        login_google: "Войти через Google",
        email_signin_tab: "Вход",
        email_signup_tab: "Регистрация",
        email_label: "Email",
        password_label: "Пароль",
        password_repeat_label: "Повторите пароль",
        show_password: "Показать",
        hide_password: "Скрыть",
        forgot_password: "Забыли пароль?",
        email_signin_button: "Войти по email",
        email_signup_button: "Зарегистрироваться",
        all_notes: "Все записи",
        favorites: "Важное",
        archive: "Архив",
        reminder_notes: "Напоминания",
        folders: "ПАПКИ",
        folders_overview: "Папки",
        about: "О нас",
        rate: "Оценить",
        settings: "Настройки",
        switch_acc: "Сменить",
        admin_tools: "Админ-меню",
        logout: "Выйти",
        empty: "Здесь пока пусто",
        general: "Общие",
        language: "Язык",
        appearance: "Внешний вид",
        presets: "Пресеты",
        manual: "Ручная настройка",
        c_text: "Текст",
        c_accent: "Акцент",
        c_bg: "Фон",
        reset: "Сбросить",
        close: "Закрыть",
        save: "Сохранить",
        team: "Команда",
        contact_us: "Связаться с нами:",
        send: "Отправить",
        cancel: "Отмена",
        yes: "Да",
        search: "Поиск...",
        note_title: "Заголовок",
        note_tags: "#тег (Enter)",
        feedback_placeholder: "Поделитесь впечатлениями...",
        note_actions: "Действия",
        audio_note: "Аудио",
        download_note: "Скачать файл",
        export_txt: "Экспорт TXT",
        export_pdf: "Экспорт PDF",
        note_trigger_analysis: "Запустить ИИ-анализ",
        note_mark_for_reanalysis: "Отметить для повторного анализа",
        share_view: "Поделиться для просмотра",
        share_edit: "Поделиться для редактирования",
        share_link_title: "Ссылка на заметку",
        share_link_placeholder: "Скопируйте ссылку",
        share_link_copied: "Ссылка скопирована",
        share_link_failed: "Не удалось создать ссылку",
        share_readonly: "Доступ только для чтения",
        share_manage_denied: "Недостаточно прав",
        photo_editor: "Редактор фото",
        folders_settings: "Папки",
        folder_view_mode: "Отображение папок в меню",
        folder_view_compact: "В боковой панели",
        folder_view_full: "Полный экран",
        reduce_motion: "Уменьшить анимации",
        visual_effects: "Визуальные эффекты",
        editor_settings: "Настройки редактора",
        view_notes: "Все записи",
        view_favorites: "Важное",
        view_archive: "Архив",
        view_reminders: "Напоминания",
        view_folder: "Папка",
        view_folders: "Папки",
        view_locked: "Защита заметок",
        reminder_empty: "Нет напоминаний",
        note_single: "заметка",
        note_plural: "заметок",
        folders_empty: "Нет папок",
        pin_note: "Закрепить",
        unpin_note: "Открепить",
        favorite_note: "Важное",
        archive_note: "Архивировать",
        restore_note: "Вернуть",
        untitled_note: "Без названия",
        empty_note: "Нет содержимого",
        locked_note: "Защищено",
        new_folder: "Новая папка",
        folder_placeholder: "Название...",
        folder_empty: "Введите название папки",
        folder_exists: "Папка уже существует",
        folder_limit: "Лимит папок достигнут",
        folder_name_too_long: "Название папки до 50 символов",
        folder_description_label: "Описание папки",
        folder_description_placeholder: "Опишите, какие заметки хранить в этой папке",
        folder_description_too_long: "Описание папки до 300 символов",
        rename_folder: "Переименовать папку",
        hide_folder: "Скрыть папку",
        show_folder: "Показать папку",
        delete_folder: "Удалить папку",
        archived: "В архиве",
        restored: "Восстановлено",
        saving: "Сохранение...",
        saved: "Сохранено",
        settings_saved: "Настройки сохранены",
        save_failed: "Не удалось сохранить",
        save_failed_quota: "Хранилище заполнено, часть старого кэша очищена",
        save_failed_storage_unavailable: "Хранилище недоступно в текущем режиме браузера",
        save_failed_fallback: "Не удалось сохранить данные в резервное хранилище",
        rate_required: "Поставьте оценку",
        feedback_thanks: "Спасибо!",
        order_updated: "Порядок обновлен",
        undo: "Отменить",
        import_file: "Импортировать файл",
        import_invalid: "Неверный формат файла",
        import_empty: "Файлы не содержат заметок",
        import_success: "Импортировано",
        load_more_notes: "Загрузить ещё",
        import_failed: "Ошибка импорта",
        feature_disabled_temporarily: "Функция временно отключена",
        download_success: "Файл сохранен",
        popup_blocked: "Разрешите всплывающие окна для печати",
        mic_unsupported: "Микрофон не поддерживается",
        mic_denied: "Нет доступа к микрофону",
        recording: "Запись...",
        confirm_delete: "Удалить?",
        confirm_exit: "Выйти?",
        confirm_account: "Сменить аккаунт?",
        confirm_delete_folder: "Удалить папку?",
        confirm_hide_folder: "Вы хотите скрыть папку?",
        confirm_default: "Подтвердите",
        auth_unavailable: "Авторизация недоступна",
        auth_fill_required: "Заполните обязательные поля",
        auth_password_short: "Пароль должен содержать минимум 6 символов",
        auth_password_mismatch: "Введите два одинаковых пароля",
        auth_email_google_only: "Этот email зарегистрирован через Google. Войдите через Google",
        auth_email_provider_conflict: "Для этого email используется другой способ входа",
        auth_email_exists: "Пользователь с таким email уже существует. Выполните вход",
        auth_email_not_found: "Аккаунт с таким email не найден",
        auth_reset_enter_email: "Введите email для восстановления пароля",
        auth_reset_sent: "Письмо для восстановления пароля отправлено",
        auth_invalid_email_format: "Введите корректный email",
        auth_google_starting: "Открываем окно входа Google...",
        auth_google_waiting: "Если окно не появилось, проверьте блокировку всплывающих окон",
        move_toolbar: "Переместить панель",
        toolbar_show: "Показать панель инструментов",
        toolbar_hide: "Скрыть панель инструментов",
        tool_bold: "Жирный",
        tool_italic: "Курсив",
        tool_underline: "Подчеркнуть",
        tool_bullets: "Маркированный список",
        tool_numbered: "Нумерованный список",
        tool_strike: "Зачеркнуть",
        tool_hr: "Горизонтальная линия",
        tool_link: "Ссылка",
        tool_note_link: "Ссылка на заметку",
        tool_image: "Изображение",
        tool_sketch: "Рисунок",
        tool_align: "Выравнивание",
        tool_clear: "Очистить формат",
        link_title: "Добавить ссылку",
        link_placeholder: "Вставьте URL",
        link_selection_required: "Выделите текст для ссылки",
        note_link_title: "Ссылка на заметку",
        note_link_placeholder: "ID заметки",
        note_link_selection_required: "Выделите текст для ссылки",
        note_link_not_found: "Заметка не найдена",
        reminder_note: "Напоминание",
        reminder_clear: "Убрать напоминание",
        reminder_saved: "Напоминание сохранено",
        analysis_completed: "ИИ-анализ завершен",
        analysis_failed: "Не удалось выполнить ИИ-анализ",
        analysis_request_sent: "Запрос отправлен. Анализ выполнится на стороне сервера",
        analysis_admin_description: "Запуск серверного анализа заметок",
        analysis_full_reindex_button: "Проиндексировать всё",
        analysis_pending_reindex_button: "Проиндексировать непроиндексированные",
        analysis_reindex_query_button: "Полная переиндексация через query-параметр",
        analysis_reindex_body_button: "Полная переиндексация через body reindexAll",
        analysis_force_reindex_button: "Полная переиндексация через body forceReindex",
        analysis_admin_secret_prompt: "Введите admin secret",
        analysis_marked_for_reanalysis: "Заметка отмечена для повторного анализа",
        reminder_cleared: "Напоминание убрано",
        reminder_required: "Выберите дату и время",
        copy_text: "Копировать текст",
        copy_success: "Скопировано",
        copy_failed: "Не удалось скопировать",
        poll: "Опрос",
        show_more: "Ещё",
        show_less: "Свернуть",
        poll_title: "Опрос",
        poll_answer_label: "Ответ",
        poll_failed: "Не удалось отправить опрос",
        poll_thanks: "Спасибо за ответ",
        survey_question: "Вопрос",
        survey_progress: "Опрос",
        survey_continue_prompt: "Хотите продолжить опрос?",
        survey_next: "Далее",
        survey_continue: "Продолжить",
        survey_finish: "Завершить",
        survey_required: "Ответьте на вопрос",
        survey_q1: "Что бы вы хотели добавить",
        survey_q2: "Какие темы и цвета вам нравятся",
        survey_q3: "Тёмная или светлая тема",
        survey_q4: "Какого функционала не хватает",
        survey_q5: "Что бы вы изменили в приложении",
        survey_q6: "Насколько удобен интерфейс",
        survey_q8: "Удобно ли писать и редактировать заметки",
        survey_q9: "Важен ли экспорт и сохранение заметок",
        survey_q10: "На какие темы вы бы добавили визуальные пресеты",
        drawing_tools: "Инструменты рисования",
        drawing_tool_pen: "Перо",
        drawing_tool_marker: "Маркер",
        drawing_tool_eraser: "Ластик",
        drawing_color: "Цвет",
        drawing_size: "Размер",
        drawing_presets: "Палитра",
        system_override: "System Override",
        close_menu: "Закрыть меню",
        add_folder: "Создать папку",
        open_menu: "Открыть меню",
        search_aria: "Поиск заметок",
        create_note: "Создать заметку",
        create_folder: "Создать папку",
        editor: "Редактор",
        back: "Назад",
        redo: "Повторить",
        delete_note: "Удалить заметку",
        note_title_aria: "Заголовок заметки",
        note_body_aria: "Текст заметки",
        note_tags_aria: "Добавить тег",
        save_note: "Сохранить",
        editor_pages: "Страницы",
        editor_pages_manage: "Управление страницами",
        page_prev: "Предыдущая страница",
        page_next: "Следующая страница",
        page_add: "Добавить страницу",
        page_select: "Выбор страницы",
        page_delete: "Удалить страницу",
        page_move_left: "Переместить страницу влево",
        page_move_right: "Переместить страницу вправо",
        page_delete_confirm: "Точно хотите удалить страницу?",
        page_delete_forbidden: "Нельзя удалить единственную страницу",
        page_title_placeholder: "Название страницы",
        prompt_title: "Ввод",
        prompt_input: "Поле ввода",
        folder_description_prompt: "Описание папки",
        ok: "ОК",
        insert: "Вставить",
        filters: "Фильтры",
        folder_actions: "Действия с папкой",
        sort_by: "Сортировка",
        sort_updated: "По времени изменения",
        sort_relevance: "По релевантности",
        sort_importance: "По важности",
        sort_title: "По алфавиту",
        sort_length: "По количеству символов",
        sort_manual: "Вручную",
        filter_folders: "Папки",
        align_menu: "Выравнивание",
        align_left: "По левому краю",
        align_center: "По центру",
        align_right: "По правому краю",
        reset_media: "Сбросить размер",
        delete: "Удалить",
        photo_color: "Цвет кисти",
        photo_width: "Толщина кисти",
        clear: "Очистить",
        folder_view_aria: "Режим отображения папок",
        color_text: "Цвет текста",
        color_accent: "Акцентный цвет",
        color_bg: "Цвет фона",
        feedback_aria: "Ваш отзыв",
        theme_light: "Светлая",
        theme_dark: "Темная",
        theme_system: "Системная",
        theme_high_contrast: "Высокий контраст",
        theme_oled: "OLED",
        theme_monochrome: "Монохром",
        theme_pastel: "Пастель",
        theme_warm: "Теплая",
        theme_cold: "Холодная",
        theme_minimal: "Минимал",
        theme_compact: "Компактная",
        theme_spacious: "Просторная",
        theme_accessibility: "Доступность",
        theme_glass: "Стекло",
        theme_matte: "Матовая",
        theme_neon: "Неон",
        theme_paper: "Бумага",
        theme_sunrise: "Рассвет",
        theme_ocean: "Океан",
        settings_menu_title: "Настройки",
        settings_general: "Общие",
        settings_appearance: "Внешний вид",
        settings_editor_tools: "Инструменты редактора",
        settings_back: "Назад",
        settings_category_general_desc: "Язык, папки и анимация",
        settings_category_appearance_desc: "Темы и цвета интерфейса",
        settings_category_editor_tools_desc: "Панель инструментов",
        settings_backgrounds: "Фоны",
        settings_transparency: "Прозрачность",
        settings_ui_opacity: "Прозрачность интерфейса",
        settings_cards_opacity: "Прозрачность заметок и папок",
        feedback_menu: "Обратная связь",
        settings_main_background: "Фон главного экрана",
        settings_sidebar_background: "Фон бокового меню",
        settings_background_placeholder: "Ссылка или данные изображения",
        settings_background_upload: "Загрузить фон",
        settings_notes_per_page: "Заметок на странице",
        smart_features: "УМНЫЕ ФУНКЦИИ",
        lock_center: "Защита заметок",
        lock_center_desc: "Тут будут фильтры скрытых заметок и быстрые действия",
        lock_center_empty: "Нет защищенных заметок",
        lock_center_masked_title: "Защищенная заметка",
        move_to_folder: "Переместить",
        folder_none: "Без папки",
        copy: "Копировать",
        apply: "Применить",
        lock_title: "Блокировка",
        lock_password: "Пароль",
        lock_password_empty: "Пароль пустой",
        lock_invalid_password: "Неверный пароль",
        lock_hidden: "Заметка скрыта",
        lock_download_blocked: "Заметка заблокирована",
        note_deleted: "Удалено",
        note_deleted_permanent: "Удалено навсегда",
        folder_deleted: "Папка удалена",
        folder_deleted_permanent: "Папка удалена навсегда",
        delete_permanently: "Удалить навсегда",
        folder_trashed: "Папка в корзине",
        hidden_folder_label: "Скрытая папка",
        hidden_folders_empty: "Скрытых папок нет",
        hidden_folders: "Скрытые папки",
        trash: "Корзина",
        feedback_failed: "Не удалось отправить отзыв",
        reorder_search_disabled: "Сортировка недоступна при поиске",
        reorder_pinned_blocked: "Закрепленные заметки сортируются отдельно",
        reorder_folder_disabled: "Сортировка доступна только внутри папки или для заметок без папки",
        reorder_sort_disabled: "Переключитесь на ручную сортировку для перемещения",
        lock_note: "Заблокировать заметку",
        unlock_note: "Открыть",
        unlock_forever: "Снять защиту",
        unlock_success: "Заметка разблокирована",
        media_photo: "фото",
        media_photos: "фото",
        media_audio: "аудио",
        media_audios: "аудио",
        nav_aria: "Навигация",
        sections_aria: "Разделы",
        notes_list_aria: "Список заметок",
        user_menu: "Пользователь",
        editor_actions: "Действия редактора",
        editor_toolbar: "Инструменты редактора",
        tags_aria: "Теги",
        media_menu: "Меню изображения",
        rating_aria: "Оценка",
        login_aria: "Авторизация",
        theme_dark_default: "Темная",
        theme_graphite: "Графит",
        theme_neon_cyan: "Неоновый циан",
        theme_emerald_calm: "Изумрудный покой",
        theme_violet_pulse: "Фиолетовый импульс",
        theme_crimson_glow: "Алый жар",
        theme_amber_wave: "Янтарная волна",
        theme_rose_blush: "Розовый румянец",
        theme_ocean_deep: "Глубокий океан",
        theme_oled_pure: "OLED черный",
        theme_manual: "Вручную",
        auth_popup_closed: "Вход отменен",
        auth_network_failed: "Нет соединения с интернетом",
        auth_cancelled: "Запрос отменен",
        logout_failed: "Ошибка при выходе",
        login_failed: "Ошибка входа",
        favorite_failed: "Не удалось обновить избранное",
        unlock_failed: "Не удалось открыть заметку",
        draw_photo_hint: "Откройте редактор фото",
        password_title: "Пароль",
        password_prompt: "Введите пароль"
    },
    en: {
        app_name: "SmartNotes",
        slogan: "Your thoughts. Organized.",
        login: "Sign in",
        login_google: "Sign in with Google",
        email_signin_tab: "Sign in",
        email_signup_tab: "Sign up",
        email_label: "Email",
        password_label: "Password",
        password_repeat_label: "Repeat password",
        show_password: "Show",
        hide_password: "Hide",
        forgot_password: "Forgot password?",
        email_signin_button: "Sign in with email",
        email_signup_button: "Create account",
        all_notes: "All Notes",
        favorites: "Important",
        archive: "Archive",
        reminder_notes: "Reminders",
        folders: "FOLDERS",
        folders_overview: "Folders",
        about: "About",
        rate: "Rate Us",
        settings: "Settings",
        switch_acc: "Switch",
        admin_tools: "Admin menu",
        logout: "Logout",
        empty: "Nothing here yet",
        general: "General",
        language: "Language",
        appearance: "Appearance",
        presets: "Presets",
        manual: "Manual Config",
        c_text: "Text",
        c_accent: "Accent",
        c_bg: "Background",
        reset: "Reset",
        close: "Close",
        save: "Save",
        team: "Team",
        contact_us: "Contact us:",
        send: "Send",
        cancel: "Cancel",
        yes: "Yes",
        search: "Search...",
        note_title: "Title",
        note_tags: "#tag (Enter)",
        feedback_placeholder: "Share your feedback...",
        note_actions: "Actions",
        audio_note: "Audio",
        download_note: "Download file",
        export_txt: "Export TXT",
        export_pdf: "Export PDF",
        note_trigger_analysis: "Run AI analysis",
        note_mark_for_reanalysis: "Mark for reanalysis",
        share_view: "Share for view",
        share_edit: "Share for edit",
        share_link_title: "Note link",
        share_link_placeholder: "Copy the link",
        share_link_copied: "Link copied",
        share_link_failed: "Unable to create link",
        share_readonly: "Read-only access",
        share_manage_denied: "Permission denied",
        photo_editor: "Photo Editor",
        folders_settings: "Folders",
        folder_view_mode: "Folder display in menu",
        folder_view_compact: "Sidebar list",
        folder_view_full: "Full view",
        reduce_motion: "Reduce motion",
        visual_effects: "Visual effects",
        editor_settings: "Editor settings",
        view_notes: "All Notes",
        view_favorites: "Important",
        view_archive: "Archive",
        view_reminders: "Reminders",
        view_folder: "Folder",
        view_folders: "Folders",
        view_locked: "Note Protection",
        reminder_empty: "No reminders",
        note_single: "note",
        note_plural: "notes",
        folders_empty: "No folders yet",
        pin_note: "Pin",
        unpin_note: "Unpin",
        favorite_note: "Favorite",
        archive_note: "Archive",
        restore_note: "Restore",
        untitled_note: "Untitled",
        empty_note: "No content",
        locked_note: "Locked",
        new_folder: "New folder",
        folder_placeholder: "Folder name",
        folder_empty: "Enter a folder name",
        folder_exists: "Folder already exists",
        folder_limit: "Folder limit reached",
        folder_name_too_long: "Folder name must be up to 50 characters",
        folder_description_label: "Folder description",
        folder_description_placeholder: "Describe what notes should go to this folder",
        folder_description_too_long: "Folder description must be up to 300 characters",
        rename_folder: "Rename folder",
        hide_folder: "Hide folder",
        show_folder: "Show folder",
        delete_folder: "Delete folder",
        archived: "Archived",
        restored: "Restored",
        saving: "Saving...",
        saved: "Saved",
        settings_saved: "Settings saved",
        save_failed: "Save failed",
        save_failed_quota: "Storage is full, part of old cache has been cleared",
        save_failed_storage_unavailable: "Storage is unavailable in current browser mode",
        save_failed_fallback: "Failed to save data in fallback storage",
        rate_required: "Please rate the app",
        feedback_thanks: "Thanks!",
        order_updated: "Order updated",
        undo: "Undo",
        import_file: "Import file",
        import_invalid: "Unsupported file",
        import_empty: "No notes found",
        import_success: "Imported",
        load_more_notes: "Load more",
        import_failed: "Import failed",
        feature_disabled_temporarily: "Feature is temporarily disabled",
        download_success: "File saved",
        popup_blocked: "Allow popups to print",
        mic_unsupported: "Microphone not supported",
        mic_denied: "Microphone access denied",
        recording: "Recording...",
        confirm_delete: "Delete?",
        confirm_exit: "Sign out?",
        confirm_account: "Switch account?",
        confirm_delete_folder: "Delete folder?",
        confirm_hide_folder: "Do you want to hide this folder?",
        confirm_default: "Confirm",
        auth_unavailable: "Authentication unavailable",
        auth_fill_required: "Fill in all required fields",
        auth_password_short: "Password must contain at least 6 characters",
        auth_password_mismatch: "Please enter matching passwords",
        auth_email_google_only: "This email is registered with Google. Please sign in with Google",
        auth_email_provider_conflict: "A different sign-in method is used for this email",
        auth_email_exists: "An account with this email already exists. Please sign in",
        auth_email_not_found: "No account found for this email",
        auth_reset_enter_email: "Enter email to reset password",
        auth_reset_sent: "Password reset email was sent",
        auth_invalid_email_format: "Enter a valid email",
        auth_google_starting: "Opening Google sign-in window...",
        auth_google_waiting: "If no window appears, check pop-up blocking settings",
        move_toolbar: "Move toolbar",
        toolbar_show: "Show toolbar",
        toolbar_hide: "Hide toolbar",
        tool_bold: "Bold",
        tool_italic: "Italic",
        tool_underline: "Underline",
        tool_bullets: "Bulleted list",
        tool_numbered: "Numbered list",
        tool_strike: "Strikethrough",
        tool_hr: "Horizontal line",
        tool_link: "Link",
        tool_note_link: "Link to note",
        tool_image: "Image",
        tool_sketch: "Sketch",
        tool_align: "Alignment",
        tool_clear: "Clear formatting",
        link_title: "Add link",
        link_placeholder: "Paste URL",
        link_selection_required: "Select text to link",
        note_link_title: "Link to note",
        note_link_placeholder: "Note id",
        note_link_selection_required: "Select text to link",
        note_link_not_found: "Note not found",
        reminder_note: "Reminder",
        reminder_clear: "Clear reminder",
        reminder_saved: "Reminder saved",
        analysis_completed: "AI analysis completed",
        analysis_failed: "AI analysis failed",
        analysis_request_sent: "Request sent. Analysis will run on the server side",
        analysis_admin_description: "Run server-side note analysis",
        analysis_full_reindex_button: "Reindex all",
        analysis_pending_reindex_button: "Reindex pending",
        analysis_reindex_query_button: "Full reindex via query parameter",
        analysis_reindex_body_button: "Full reindex via body reindexAll",
        analysis_force_reindex_button: "Full reindex via body forceReindex",
        analysis_admin_secret_prompt: "Enter admin secret",
        analysis_marked_for_reanalysis: "Note marked for reanalysis",
        reminder_cleared: "Reminder removed",
        reminder_required: "Pick date and time",
        copy_text: "Copy text",
        copy_success: "Copied",
        copy_failed: "Copy failed",
        poll: "Poll",
        show_more: "More",
        show_less: "Less",
        poll_title: "Poll",
        poll_answer_label: "Answer",
        poll_failed: "Unable to send poll",
        poll_thanks: "Thanks for your answer",
        survey_question: "Question",
        survey_progress: "Survey",
        survey_continue_prompt: "Would you like to continue the survey?",
        survey_next: "Next",
        survey_continue: "Continue",
        survey_finish: "Finish",
        survey_required: "Please answer the question",
        survey_q1: "What would you like to add",
        survey_q2: "What themes and colors do you like",
        survey_q3: "Dark or light theme",
        survey_q4: "What functionality is missing",
        survey_q5: "What would you change in the app",
        survey_q6: "How convenient is the interface",
        survey_q8: "Is it convenient to write and edit notes",
        survey_q9: "Is export and saving important",
        survey_q10: "What topics would you add visual presets for",
        drawing_tools: "Drawing tools",
        drawing_tool_pen: "Pen",
        drawing_tool_marker: "Marker",
        drawing_tool_eraser: "Eraser",
        drawing_color: "Color",
        drawing_size: "Size",
        drawing_presets: "Palette",
        system_override: "System Override",
        close_menu: "Close menu",
        add_folder: "Create folder",
        open_menu: "Open menu",
        search_aria: "Search notes",
        create_note: "Create note",
        create_folder: "Create folder",
        editor: "Editor",
        back: "Back",
        redo: "Redo",
        delete_note: "Delete note",
        note_title_aria: "Note title",
        note_body_aria: "Note body",
        note_tags_aria: "Add tag",
        save_note: "Save",
        editor_pages: "Pages",
        editor_pages_manage: "Manage pages",
        page_prev: "Previous page",
        page_next: "Next page",
        page_add: "Add page",
        page_select: "Select page",
        page_delete: "Delete page",
        page_move_left: "Move page left",
        page_move_right: "Move page right",
        page_delete_confirm: "Are you sure you want to delete this page?",
        page_delete_forbidden: "You cannot delete the only page",
        page_title_placeholder: "Page name",
        prompt_title: "Input",
        prompt_input: "Input field",
        folder_description_prompt: "Folder description",
        ok: "OK",
        insert: "Insert",
        filters: "Filters",
        folder_actions: "Folder actions",
        sort_by: "Sort by",
        sort_updated: "Recently updated",
        sort_relevance: "Relevance",
        sort_importance: "Importance",
        sort_title: "Title (A–Z)",
        sort_length: "Character count",
        sort_manual: "Manual",
        filter_folders: "Folders",
        align_menu: "Alignment",
        align_left: "Align left",
        align_center: "Align center",
        align_right: "Align right",
        reset_media: "Reset size",
        delete: "Delete",
        photo_color: "Brush color",
        photo_width: "Brush width",
        clear: "Clear",
        folder_view_aria: "Folder view mode",
        color_text: "Text color",
        color_accent: "Accent color",
        color_bg: "Background color",
        feedback_aria: "Your feedback",
        theme_light: "Light",
        theme_dark: "Dark",
        theme_system: "System",
        theme_high_contrast: "High Contrast",
        theme_oled: "OLED",
        theme_monochrome: "Monochrome",
        theme_pastel: "Pastel",
        theme_warm: "Warm",
        theme_cold: "Cold",
        theme_minimal: "Minimal",
        theme_compact: "Compact",
        theme_spacious: "Spacious",
        theme_accessibility: "Accessibility",
        theme_glass: "Glass",
        theme_matte: "Matte",
        theme_neon: "Neon",
        theme_paper: "Paper",
        theme_sunrise: "Sunrise",
        theme_ocean: "Ocean",
        settings_menu_title: "Settings",
        settings_general: "General",
        settings_appearance: "Appearance",
        settings_editor_tools: "Editor Tools",
        settings_back: "Back",
        settings_category_general_desc: "Language, folders, motion",
        settings_category_appearance_desc: "Themes and interface colors",
        settings_category_editor_tools_desc: "Toolbar tools",
        settings_backgrounds: "Backgrounds",
        settings_transparency: "Transparency",
        settings_ui_opacity: "Interface opacity",
        settings_cards_opacity: "Notes and folders opacity",
        feedback_menu: "Feedback",
        settings_main_background: "Main screen background",
        settings_sidebar_background: "Sidebar background",
        settings_background_placeholder: "Image URL or data",
        settings_background_upload: "Upload background",
        settings_notes_per_page: "Notes per page",
        smart_features: "SMART FEATURES",
        lock_center: "Note Protection",
        lock_center_desc: "Hidden notes filters and quick actions will appear here",
        lock_center_empty: "No protected notes",
        lock_center_masked_title: "Protected note",
        move_to_folder: "Move",
        folder_none: "No folder",
        copy: "Copy",
        apply: "Apply",
        lock_title: "Lock",
        lock_password: "Password",
        lock_password_empty: "Password is empty",
        lock_invalid_password: "Invalid password",
        lock_hidden: "Note hidden",
        lock_download_blocked: "Note is locked",
        note_deleted: "Deleted",
        note_deleted_permanent: "Deleted permanently",
        folder_deleted: "Folder deleted",
        folder_deleted_permanent: "Folder deleted permanently",
        delete_permanently: "Delete permanently",
        folder_trashed: "Folder in trash",
        hidden_folder_label: "Hidden folder",
        hidden_folders_empty: "No hidden folders",
        hidden_folders: "Hidden folders",
        trash: "Trash",
        feedback_failed: "Unable to send feedback",
        reorder_search_disabled: "Reordering is disabled while searching",
        reorder_pinned_blocked: "Pinned notes reorder separately",
        reorder_folder_disabled: "Reordering is available only inside folders or for notes without folders",
        reorder_sort_disabled: "Switch to manual sorting to reorder",
        lock_note: "Lock note",
        unlock_note: "Unlock",
        unlock_forever: "Remove lock",
        unlock_success: "Note unlocked",
        media_photo: "photo",
        media_photos: "photos",
        media_audio: "audio",
        media_audios: "audio",
        nav_aria: "Navigation",
        sections_aria: "Sections",
        notes_list_aria: "Notes list",
        user_menu: "User menu",
        editor_actions: "Editor actions",
        editor_toolbar: "Editor toolbar",
        tags_aria: "Tags",
        media_menu: "Image menu",
        rating_aria: "Rating",
        login_aria: "Authentication",
        theme_dark_default: "Dark Default",
        theme_graphite: "Graphite",
        theme_neon_cyan: "Neon Cyan",
        theme_emerald_calm: "Emerald Calm",
        theme_violet_pulse: "Violet Pulse",
        theme_crimson_glow: "Crimson Glow",
        theme_amber_wave: "Amber Wave",
        theme_rose_blush: "Rose Blush",
        theme_ocean_deep: "Ocean Deep",
        theme_oled_pure: "OLED Pure",
        theme_manual: "Manual",
        auth_popup_closed: "Sign-in canceled",
        auth_network_failed: "No internet connection",
        auth_cancelled: "Request canceled",
        logout_failed: "Sign out failed",
        login_failed: "Sign-in failed",
        favorite_failed: "Unable to update favorite",
        unlock_failed: "Unable to unlock note",
        draw_photo_hint: "Open the photo editor",
        password_title: "Password",
        password_prompt: "Enter password"
    }
}

window.LANG = LANG
